name: pr

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - uses: gradle/gradle-build-action@v2.1.4

      - name: Install libcurl
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev

      - name: Build with Gradle
        run: ./gradlew linkReleaseExecutableLinuxX64

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mastodon-to-rss:latest
