name: pr

on: pull_request

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28 #v3
      - uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3 #v3
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee #v2.1.4
      - name: Install cURL Headers
        run: sudo apt-get update && sudo apt-get install libcurl3-openssl-dev
      - name: Build with Gradle
        run: ./gradlew linkDebugExecutableLinuxX64 linkReleaseExecutableLinuxX64
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 #v3
        with:
          name: binaries
          path: build/bin/linuxX64/
